group mixed precision website
EmoryMLIP/emory-reu-ret-website pull request #10
Opened 2022-07-08 18:55 UTC by kristinagxy

update mixed precision website

2022-07-25 15:07 UTC, lruthotto commented on content/projects/2022-mixed-precision/index.md
> +Figure 1: screenshot from <em>the Legend of Zelda - Breath of the Wild</em>
What is the copyright situation for the screenshot?

2022-07-25 15:09 UTC, lruthotto commented on content/projects/2022-mixed-precision/index.md
> +The Chebyshev Semi-Iterative (CS) Method requires no inner product computation, which is great because it will cause overflow easily in CG. But there is always the trade-off! The CS method needs the
Can you provide a link?

2022-07-25 15:12 UTC, kristinagxy commented on content/projects/2022-mixed-precision/index.md
> +<img src="img/IEEE.png" alt="drawing" width="500"/>
it is a screenshot I took from a game. shall I provide a reference to the game?

2022-07-25 15:12 UTC, lruthotto requested changes
Hi y'all,

Thanks for improving the blog post. We're almost done here. Please take a look at my updated comments and message me on slack if you have more questions.

2022-07-25 15:12 UTC, lruthotto commented on content/projects/2022-mixed-precision/index.md
> +The [conjugate gradient algorithm](https://www.cs.cmu.edu/~quake-papers/painless-conjugate-gradient.pdf) aims to solve the linear system Ax = b where A is SPD (symmetric and positive definite),transf
Note also that you use CGLS later. Want to link to this method instead?

2022-07-25 15:12 UTC, lruthotto commented on content/projects/2022-mixed-precision/index.md
> +### Image Deblurring Using CGLS with regularizationand
typo?

2022-07-25 15:12 UTC, lruthotto commented on content/projects/2022-mixed-precision/index.md
> +
Think about how you want to end the article? Is there a conclusion/summary of the experiment? Or do you want to add pictures and short bios?

2022-07-31 11:57 UTC, lruthotto commented on content/projects/2022-mixed-precision/index.md
> +<img src="img/IEEE.png" alt="drawing" width="500"/>
yes, at the very least do that. I am not familiar what the situation for screenshots is like. Reading the text again, makes me wonder how essential the image here is. There is not much explanation, why the image is there, correct?

2022-07-31 11:57 UTC, lruthotto commented on content/projects/2022-mixed-precision/index.md
> +<img src="img/IEEE.png" alt="drawing" width="500"/>
In that case, it might be better to just remove the image.

2022-08-01 14:09 UTC, kristinagxy commented on content/projects/2022-mixed-precision/index.md
> +<img src="img/IEEE.png" alt="drawing" width="500"/>
> In that case, it might be better to just remove the image.

Yes we have removed the image. Thank you!

2023-04-27 17:10 UTC, merged