Rough draft web RL
EmoryMLIP/emory-reu-ret-website pull request #13
Opened 2022-07-08 20:44 UTC by jacmantooth

2022-07-08 20:45 UTC, jacmantooth commented
Hey lars here is our website

2022-07-18 15:14 UTC, lruthotto requested changes
Great first draft, y'all. Please look at my comments inline and push any changes to this branch .

2022-07-18 15:14 UTC, lruthotto commented on content/projects/2022-rl-vs-oc/index.md
> +summary: 'In recent years, reinforcement learning (RL) methods have shown success in solving optimal control problems involving ordinary differential equations. RL approaches differ drastically from
Instead of 'this paper' say something like in this 'REU project'?

2022-07-18 15:14 UTC, lruthotto commented on content/projects/2022-rl-vs-oc/index.md
> +summary: 'In recent years, reinforcement learning (RL) methods have shown success in solving optimal control problems involving ordinary differential equations. RL approaches differ drastically from
Also, last sentence to be completed.

2022-07-18 15:14 UTC, lruthotto commented on content/projects/2022-rl-vs-oc/index.md
> +This blog post was written by Jacob Mantooth,Dewan Chowdhury, Arjun Sethi-Olowin and with the help of our advisory Dr.Ruthotto.
1) Not sure I helped.
2) if you have personal websites, add links!

2022-07-18 15:14 UTC, lruthotto commented on content/projects/2022-rl-vs-oc/index.md
> +The word around town is that reinforcement learning is the top dog and has the answers to all our problems. We wanted to see if that really was the case, so this summer we took a trip to Emory Univer
I like it! Consider making a few paragraphs (easier to read online)

2022-07-18 15:14 UTC, lruthotto commented on content/projects/2022-rl-vs-oc/index.md
> +### The Why???
Be more specific: Why this problem?

2022-07-18 15:14 UTC, lruthotto commented on content/projects/2022-rl-vs-oc/index.md
> +Our first method that we looked at during this REU was the local method. In this approach we found the local solution using numerical ODE solvers and Nonlinear Optimization.
'a local method'

2022-07-18 15:14 UTC, lruthotto commented on content/projects/2022-rl-vs-oc/index.md
> +![H. Giang, T. Hoan, P. Thanh, and I. Koo. Hybrid noma/oma-based dynamic power allocation scheme using deep reinforcement learning in 5g networks. Applied Sciences, 10(12), 2020.](img/actor-critic.pn
what's the copyright on this? If there is a doubt, better not have it.

2022-07-18 15:14 UTC, lruthotto commented on content/projects/2022-rl-vs-oc/index.md
> +Some useful background in our reinforcement learning method is that we were working in the OpenAI gym mountain car environment, so we were able to find preexisting code for our project. The thing is
could end up in the 'why' section?

2022-07-18 15:14 UTC, lruthotto commented on content/projects/2022-rl-vs-oc/index.md
> +### Week 4 & 5
to be completed!

2022-07-26 17:54 UTC, lruthotto requested changes
Sorry I didn't submit all the comments for my review.

2022-08-09 15:07 UTC, merged

2022-08-09 15:07 UTC, lruthotto commented
Great job, guys. I've merged this now!