Carl Yang team website draft
EmoryMLIP/emory-reu-ret-website pull request #15
Opened 2022-07-09 03:00 UTC by ericaychoi

2022-07-18 14:57 UTC, lruthotto requested changes
Dear team

Thanks for sending your website draft. This all looks good, but I have a few suggestions. 
1) Keep in mind that this blog post will host a link to the paper. I could imagine that some things (like the tables and experimental setup) are best discussed there. That way, you can focus the website on a high level description of your REU experience and motivate people to read on. 
2) Please confirm that all the graphics were generated by you, so I know we have the copyright.

Thanks,
Lars

2022-07-18 14:57 UTC, lruthotto commented on content/projects/2022-brain-nets/index.md
> +# Overview: Comparing Shallow vs. Deep Brain Network Models
Suggestion: remove the 'overview'.

2022-07-18 14:57 UTC, lruthotto commented on content/projects/2022-brain-nets/index.md
> +We are comparing and benchmarking the performance of graph kernels and graph neural networks applied to disease classification based on neuroimaging data.
Do you want to specify who is 'we'? I'll use the first paragraph later to link your paper and other materials you've created.

2022-07-18 16:21 UTC, ericaychoi commented
Hi Professor Ruthotto,

Thank you for your feedback. We have some changes to the website that we
have made since the last pull request, so would it be okay for me to
incorporate your feedback and make another pull request later today?

Best,
Erica

On Mon, Jul 18, 2022 at 10:57 AM Lars Ruthotto ***@***.***>
wrote:

> ***@***.**** requested changes on this pull request.
>
> Dear team
>
> Thanks for sending your website draft. This all looks good, but I have a
> few suggestions.
>
>    1. Keep in mind that this blog post will host a link to the paper. I
>    could imagine that some things (like the tables and experimental setup) are
>    best discussed there. That way, you can focus the website on a high level
>    description of your REU experience and motivate people to read on.
>    2. Please confirm that all the graphics were generated by you, so I
>    know we have the copyright.
>
> Thanks,
> Lars
> ------------------------------
>
> In content/projects/2022-brain-nets/index.md
> <https://github.com/EmoryMLIP/emory-reu-ret-website/pull/15#discussion_r923471146>
> :
>
> >  tags: ["Summer 2022"]
>  ---
> +# Overview: Comparing Shallow vs. Deep Brain Network Models
>
> Suggestion: remove the 'overview'.
> ------------------------------
>
> In content/projects/2022-brain-nets/index.md
> <https://github.com/EmoryMLIP/emory-reu-ret-website/pull/15#discussion_r923473375>
> :
>
> >  tags: ["Summer 2022"]
>  ---
> +# Overview: Comparing Shallow vs. Deep Brain Network Models
> +
> +We are comparing and benchmarking the performance of graph kernels and graph neural networks applied to disease classification based on neuroimaging data.
>
> Do you want to specify who is 'we'? I'll use the first paragraph later to
> link your paper and other materials you've created.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/EmoryMLIP/emory-reu-ret-website/pull/15#pullrequestreview-1041994854>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AZFVFC5SVZSB3227SALNPFDVUVWG7ANCNFSM53CUWWTQ>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2022-07-19 21:48 UTC, ericaychoi commented
Hi Professor Ruthotto, 

My team has made some updates and have addressed your last feedback. Please let us know if there are any other concerns regarding our website. Thank you!

Best,
Erica

2022-07-25 15:32 UTC, lruthotto approved these changes
Thanks for the revision. This looks good to go! I may do some minor edits before uploading it.

2022-07-25 15:32 UTC, merged