Team JFB website
EmoryMLIP/emory-reu-ret-website pull request #18
Opened 2022-07-23 04:06 UTC by lisazhao513

2022-07-25 15:48 UTC, lruthotto requested changes
Good job, team. This looks really nice, but I left a few easy-to-address comments for you to fix. Please write me on slack if you have questions about any of these.

2022-07-25 15:48 UTC, lruthotto commented on content/projects/2022-implicit/index.md
> +In order to minimize the noise factor, we want to formulate an optimization problem.
I'd argue that you want to formulate a *regularized* optimization problem.

2022-07-25 15:48 UTC, lruthotto commented on content/projects/2022-implicit/index.md
> +However, this creates some problems concerning memory cost and the number of layers, $K$, in our neural network. The memory grows linearly as $K$—chosen heuristically—increases.
Also, is this point obvious or do you want to reference a paper where I can see why this is the case?

2022-07-25 15:48 UTC, lruthotto commented on content/projects/2022-implicit/index.md
> +To circumvent this issue, we use a recently proposed method called Jacobian-Free Backpropagation.
link the paper?

2022-07-25 15:48 UTC, lruthotto commented on content/projects/2022-implicit/index.md
> +We sincerely thank the guidance of our mentor, Dr. Samy Wu Fung, and other mentors at Emory University for the opportunity. This work is supported in part by the US National Science Foundation awards
No need to list the grants here. They are listed on our main website.  OK of course to leave the first sentence if you like.

2022-07-26 03:02 UTC, lliu58b commented on content/projects/2022-implicit/index.md
> +However, this creates some problems concerning memory cost and the number of layers, $K$, in our neural network. The memory grows linearly as $K$—chosen heuristically—increases.
capitalized K is the number of layers. small k is the iteration index. This is indeed a bit confusing. should we change it to another index like j? 

This point is from this IEEE paper <https://ieeexplore.ieee.org/document/9565378>, on page 1124, section II.A.

2022-07-26 17:52 UTC, lruthotto commented on content/projects/2022-implicit/index.md
> +However, this creates some problems concerning memory cost and the number of layers, $K$, in our neural network. The memory grows linearly as $K$—chosen heuristically—increases.
Now that K is defined this is better. Do you want to link the paper?

2022-07-27 15:18 UTC, lruthotto commented
Looks good to me now! Thanks a lot.

2022-07-27 15:18 UTC, merged